version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: razdeepak
      MYSQL_DATABASE: exam

  spring-boot-app:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/exam
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: razdeepak
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect  # Change the dialect based on your MySQL version
      SPRING_JPA_PROPERTIES_HIBERNATE_CHARSET: utf8mb4  # Character encoding configuration
