server:
  port: 9000
spring:
  cors:
    allow-credentials: true
    allowed-headers: '*'
    allowed-methods: GET, POST, PUT, DELETE
    allowed-origins: http://localhost:4200
  datasource:
    password: razdeepak
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/exam
    username: root
    hikari:
      connectionTimeout: 30000
      idleTimeout: 30000
      leak-detection-threshold: 2100
      maxLifetime: 2000000
      maximumPoolSize: 20
      minimumIdle: 1
      poolName: SpringBootJPAHikariCP
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#
#  main:
#    allow-circular-references: true